export { default as AllProductsButton } from './atoms/allProductsButton/AllProductsButton';
export { default as Icon } from './atoms/iconComponent/Icon';
export { default as Img } from './atoms/imgComponent/Img';
export { default as Modal } from './atoms/modal/Modal';
export * from './index';
export { default as HeroItem } from './molecules/heroItem/HeroItem';
export { default as ProductsCards } from './molecules/productsCards/ProductsCards';
export { default as ProductsNav } from './molecules/productsNav/ProductsNav';
export { default as Hero } from './organisms/hero/Hero';
export { default as ProductsContainer } from './organisms/productsContainer/ProductsContainer';
export { default as Home } from './pages/Home';
export { default as Products } from './pages/Products';
export { default as HomeTemplate } from './templates/homeTemplate/HomeTemplate';
export { default as ProductsTemplate } from './templates/productsTemplates/ProductsTemplate';
