export { default as AllProductsButton } from './atoms/allProductsButton/AllProductsButton';
export { default as Icon } from './atoms/iconComponent/Icon';
export { default as Img } from './atoms/imgComponent/Img';
export * from './index';
export { default as HeroItem } from './molecules/heroItem/HeroItem';
export { default as Hero } from './organisms/hero/Hero';
export { default as Home } from './pages/Home';
export { default as Products } from './pages/Products';
export { default as HomeTemplate } from './templates/homeTemplate/HomeTemplate';
export { default as AllProductsTemplate } from './templates/productsTemplates/AllProductsTemplate';
export { default as ColdProductsTemplate } from './templates/productsTemplates/ColdProductsTemplate';
export { default as HotProductsTemplate } from './templates/productsTemplates/HotProductsTemplate';
